// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: commonpb/common.proto

/* eslint-disable */

export const protobufPackage = "purpl3shadow.commonpb";

export interface IDVersion {
  id: number;
  updatedAt: Date | undefined;
}
