version: "2"

linters:
  default: all

  disable:
    - depguard
    - wsl
    - gomodguard
    - revive
    - exhaustruct
    - varnamelen

  enable:
    - wsl_v5
    - gomodguard_v2

  settings:
    wrapcheck:
      ignore-package-globs:
        - "github.com/vandad1901/p3s/packages/go/*"
    depguard:
      rules:
        default:
          list-mode: lax
          files:
            - $all
            - "!$test"
          allow:
            - $all
run:
  build-tags:
    - test
