set shell := ["sh", "-cu"]
set dotenv-load

### Style

RED := '\033[0;31m'
GREEN := '\033[0;32m'
YELLOW := '\033[1;33m'
BLUE := '\033[0;34m'
NORMAL := '\033[0m'

@run:
    go run ./cmd/server/

@test:
    go test -tags test ./...

@db-reset:
    just db-up

@db-up:
    echo "{{ YELLOW }}[i] {{ BLUE }}media{{ NORMAL }} Applying migrations to database"
    migrate -database "postgres://$MEDIA_PG_USER:$MEDIA_PG_PASSWORD@$MEDIA_PG_HOST:$MEDIA_PG_PORT/$MEDIA_PG_DATABASE?sslmode=disable&x-migrations-table=media_schema_migrations" -path ./migrations up
