set shell := ["sh", "-cu"]
set dotenv-load

###Style

RED := '\033[0;31m'
GREEN := '\033[0;32m'
YELLOW := '\033[1;33m'
BLUE := '\033[0;34m'
NORMAL := '\033[0m'

@run:
    go run ./cmd/server/

@test:
    go test -tags test ./...

@db-reset:
    echo "{{ YELLOW }}[i] {{ RED }}Dropping{{ NORMAL }} database: {{ BLUE }}auth{{ NORMAL }}"
    PGPASSWORD="$AUTH_PG_PASSWORD" dropdb --force --if-exists -h "$AUTH_PG_HOST" -p "$AUTH_PG_PORT" -U "$AUTH_PG_USER" "$AUTH_PG_DATABASE"
    echo "{{ YELLOW }}[i] {{ GREEN }}Creating{{ NORMAL }} database: {{ BLUE }}auth{{ NORMAL }}"
    PGPASSWORD="$AUTH_PG_PASSWORD" createdb -h "$AUTH_PG_HOST" -p "$AUTH_PG_PORT" -U "$AUTH_PG_USER" "$AUTH_PG_DATABASE"
    echo "{{ YELLOW }}[i]{{ NORMAL }} Applying migrations to database: {{ BLUE }}auth{{ NORMAL }}"
    migrate -database "postgres://$AUTH_PG_USER:$AUTH_PG_PASSWORD@$AUTH_PG_HOST:$AUTH_PG_PORT/$AUTH_PG_DATABASE?sslmode=disable" -path ./migrations up
