// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: postpb/post.proto

/* eslint-disable */

export const protobufPackage = "purpl3shadow.postpb";

export interface Post {
  id: number;
  authorId: number;
  content: string;
  createdAt: Date | undefined;
}
