syntax = "proto3";

option go_package = "github.com/vandad1901/p3s/packages/go/gen/protobuf/postpb/v1;postpb";
package api.postpb.v1;

import "google/protobuf/timestamp.proto";

import "google/api/annotations.proto";

import "commonpb/v1/common.proto";

service PostService {
  rpc Create (CreateRequest) returns (CreateResponse)
  {
    option (google.api.http) = {
      post: "/api/v1/post"
      body: "post"
    };
  };
  rpc Get (GetRequest) returns (GetResponse)
  {
    option (google.api.http) = {
      get: "/api/v1/post/{id}"
    };
  };
  rpc Update (UpdateRequest) returns (UpdateResponse) {
    option (google.api.http) = {
      patch: "/api/v1/post"
      body : "post"
    };
  };
  rpc Delete (DeleteRequest) returns (DeleteResponse) {
    option (google.api.http) = {
      delete: "/api/v1/post/{id}"
    };
  };
}

enum PostStatus {
  POST_STATUS_UNSPECIFIED = 0;
  POST_STATUS_DRAFT       = 1;
  POST_STATUS_PUBLISHED   = 2;
}

message Post {
  int64 id = 1;

  string     title       = 2;
  string     slug        = 3;
  PostStatus post_status = 4;

  google.protobuf.Timestamp created_at = 5;
  int64                     created_by = 6;
  google.protobuf.Timestamp updated_at = 7;
  int64                     updated_by = 8;
}

enum BlockType {
  BLOCK_TYPE_UNSPECIFIED = 0;
  BLOCK_TYPE_HEADER      = 1;
  BLOCK_TYPE_TEXT        = 2;
}

message PostBlock {
  int64 id       = 1;
  int64 post_id  = 2;
  int32 position = 3;

  BlockType block_type = 4;
  string    media      = 5;
  string    text       = 6;
}

message CreateRequest {
  Post               post        = 1;
  repeated PostBlock post_blocks = 2;
}

message CreateResponse {
  commonpb.v1.IDVersion id_version = 1;
}

message GetRequest {
  int64 id = 1;
}

message GetResponse {
  Post               post        = 1;
  repeated PostBlock post_blocks = 2;
}

message PostBlockUpdateRequest {
  repeated PostBlock inserted = 1;
  repeated PostBlock updated  = 2;
  repeated int64     deleted  = 3;
}

message UpdateRequest {
  Post                   post               = 1;
  PostBlockUpdateRequest post_block_request = 2;
}

message UpdateResponse {
  commonpb.v1.IDVersion id_version = 1;
}

message DeleteRequest {
  int64                     id         = 1;
  google.protobuf.Timestamp updated_at = 2;
}

message DeleteResponse {}
