name: p3s

services:
  pgadmin:
    image: docker.io/dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8885:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  pg:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_PG_USER} # shared with api service
      POSTGRES_PASSWORD: ${AUTH_PG_PASSWORD} # shared with api service
    ports:
      - "${AUTH_PG_PORT}:5432" # shared with api service
    volumes:
      - pg_data:/var/lib/postgresql/data

  silo:
    image: pgsty/silo:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${UPLOAD_S3_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${UPLOAD_S3_ROOT_PASSWORD}
    ports:
      - "${UPLOAD_S3_PORT}:9000"
      - "9001:9001"
    volumes:
      - silo_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "silo", "healthcheck", "ready" ]
      interval: 30s

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ../../apps/envoy:/etc/envoy
    # depends_on:
    #   - auth

volumes:
  pg_data:
  silo_data:
  pgadmin_data:

