name: p3s

services:
  auth:
    build:
      context: ../..
      dockerfile: ./apps/auth/dockerfile
    restart: unless-stopped
    env_file:
      - ../../apps/auth/.env
    environment:
      - AUTH_PG_HOST=auth-pg
    volumes:
      - ../../apps/auth/jwt_private_key.pem:/app/jwt_private_key.pem
    depends_on:
      - auth-pg
