name: purpl3shadow

services:
  pgadmin:
    image: docker.io/dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8885:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  auth-pg:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_PG_USER}
      POSTGRES_PASSWORD: ${AUTH_PG_PASSWORD}
      POSTGRES_DB: ${AUTH_PG_DATABASE}
    ports:
      - "${AUTH_PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  pgadmin_data:

networks:
  envoy-net:
    driver: overlay
