name: p3s

services:
  auth:
    build:
      context: ../..
      dockerfile: ./apps/auth/dockerfile
    restart: unless-stopped
    env_file:
      - ../../apps/auth/.env
    volumes:
      - ../../apps/auth/jwt_private_key.pem:/app/jwt_private_key.pem
    depends_on:
      - pg
  api:
    build:
      context: ../..
      dockerfile: ./apps/api/dockerfile
    restart: unless-stopped
    env_file:
      - ../../apps/api/.env
    depends_on:
      - pg
