name: purpl3shadow

services:
  auth:
    build:
      context: ../..
      dockerfile: ./apps/auth/dockerfile

    restart: unless-stopped
    env_file:
      - ../../apps/auth/.env
    ports:
      - "8080:8080"
    depends_on:
      - auth-pg
    networks:
      - envoy-net
