syntax = "proto3";

option go_package = "github.com/vandad1901/purpl3shadow/packages/go/protobuf/userpb;userpb";
package userpb.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service UserService {
  rpc Register (RegisterRequest) returns (RegisterResponse)
  {
    option (google.api.http) = {
      post: "/v1/auth/register"
      body: "*"
    };
  };
  rpc Login (LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/v1/auth/login"
      body: "*"
    };
  };
  rpc RefreshJWT (RefreshJWTRequest) returns (RefreshJWTResponse) {
    option (google.api.http) = {
      post: "/v1/auth/refresh"
      body: "*"
    };
  };
  rpc GetUser (GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/v1/users/{id}"
    };
  };
}

message User {
  int64  id       = 1;
  string username = 2;
  string email    = 3;
}

enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0;
  SESSION_STATUS_ACTIVE      = 1;
  SESSION_STATUS_REVOKED     = 2;
}

message AuthSessionResponse {
  string                    jwt               = 1;
  string                    refresh_token     = 2;
  google.protobuf.Timestamp access_expires_at = 3;
}

message RegisterRequest {
  User   user     = 1;
  string password = 2;
}

message RegisterResponse {
  AuthSessionResponse session = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  AuthSessionResponse session = 1;
}

message RefreshJWTRequest {
  string refresh_token = 1;
}

message RefreshJWTResponse {
  AuthSessionResponse session = 1;
}

message GetUserRequest {
  int64 id = 1;
}

message GetUserResponse {
  User user = 1;
}