syntax = "proto3";

option go_package = "github.com/vandad1901/p3s/packages/go/gen/protobuf/media/mediapb/v1;mediapb";
package media.mediapb.v1;

import "google/api/annotations.proto";

service MediaService {
  rpc MediaIngested(MediaIngestedRequest) returns (MediaIngestedResponse) {
    option (google.api.http) = {
      post: "/media/v1/ingested"
      body: "*"
    };
  }
  rpc GetMedia(GetMediaRequest) returns (GetMediaResponse) {}
}

message MediaIngestedRequest {
  repeated string media_keys = 1;
}

message MediaIngestedResponse {
  int64 unfinished = 1;
}

message GetMediaRequest  {
  repeated string media_keys = 1;
}

message GetMediaResponse {
  repeated MediaInfo media = 1;
}

message Derivative {
  int32  width = 1;
  string url   = 2;
}

message MediaInfo {
  string              media_key   = 1;
  int32               width       = 2;
  int32               height      = 3;
  repeated Derivative derivatives = 4;
}