FROM golang:1.26.3-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux \
    go build -ldflags="-w -s" -o main ./apps/api/cmd/server

FROM gcr.io/distroless/static-debian13:nonroot
WORKDIR /app

COPY --from=builder /app/main /app/main

ENTRYPOINT ["/app/main"]