set shell := ["sh", "-cu"]
set dotenv-load

### Style

RED := '\033[0;31m'
GREEN := '\033[0;32m'
YELLOW := '\033[1;33m'
BLUE := '\033[0;34m'
NORMAL := '\033[0m'

@run:
    go run ./cmd/server/

@test:
    go test -tags test ./...

@db-reset:
    just db-down
    just db-up

@db-up:
    echo "{{ YELLOW }}[i] {{ BLUE }}API{{ NORMAL }} {{ GREEN }}Creating{{ NORMAL }} database"
    PGPASSWORD="$API_PG_PASSWORD" createdb -h "$API_PG_HOST" -p "$API_PG_PORT" -U "$API_PG_USER" "$API_PG_DATABASE"
    echo "{{ YELLOW }}[i] {{ BLUE }}API{{ NORMAL }} Applying migrations to database"
    migrate -database "postgres://$API_PG_USER:$API_PG_PASSWORD@$API_PG_HOST:$API_PG_PORT/$API_PG_DATABASE?sslmode=disable&x-migrations-table=api_schema_migrations" -path ./migrations up

@db-down:
    echo "{{ YELLOW }}[i] {{ BLUE }}API{{ NORMAL }} {{ RED }}Dropping{{ NORMAL }} database"
    PGPASSWORD="$API_PG_PASSWORD" dropdb --force --if-exists -h "$API_PG_HOST" -p "$API_PG_PORT" -U "$API_PG_USER" "$API_PG_DATABASE"
