name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test

      AUTH_PG_HOST: localhost
      AUTH_PG_PORT: 5432
      AUTH_PG_USER: postgres
      AUTH_PG_PASSWORD: postgres
      AUTH_PG_DATABASE: auth

      API_PG_HOST: localhost
      API_PG_PORT: 5432
      API_PG_USER: postgres
      API_PG_PASSWORD: postgres
      API_PG_DATABASE: api

      JWT_PRIVATE_KEY_PATH: "./jwt_private_key.pem"
      KEYSET_KEY_ID: "auth-key-1"

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - run: mise exec -- just dev
      - run: mise exec -- just db-up
      - run: mise exec -- just test
